---
- name: Ubuntu Block
  block:
    - name: Debian - Update Cache
      apt: update_cache=yes
      changed_when: false

    - name: Install Dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ dependencies }}"

    - name: Install new MOTD files
      template:
        src: "templates/{{ item }}.j2"
        dest: "/etc/update-motd.d/{{ item }}"
        owner: root
        group: root
        mode: 0755
      with_items: "{{ motd_files }}"

    - name: Get all files currently in motd folder
      command: find /etc/update-motd.d/ -maxdepth 1 -type f -printf '%f\n'
      register: current_file_list
      changed_when: false

    - name: Delete any old MOTD files
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      with_items: "{{ current_file_list.stdout_lines }}"
      when: item not in motd_files

  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "17"

- name: CentOS Block
  block:

    - name: Install Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - ruby
        - figlet

    - name: Install lolcat gem
      gem:
        name: lolcat
        state: present
        user_install: false

    - name: Create Directory for MOTD Scripts
      file:
        path: /usr/local/bin/motd-scripts
        state: directory

    - name: Install new MOTD files
      template:
        src: "templates/{{ item }}.j2"
        dest: "/usr/local/bin/motd-scripts/{{ item }}"
        owner: root
        group: root
        mode: 0755
        force: true
      with_items: "{{ motd_files }}"

    - name: Install Login Script
      template:
        src: "templates/login-info.j2"
        dest: "/etc/profile.d/login-info.sh"
        owner: root
        group: root
        mode: 0755
      with_items: "{{ motd_files }}"

  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
